//! Full Demo - Actually calling C functions from Rust via FFI

mod ffi {
    include!(concat!(env!("OUT_DIR"), "/calculator_bindings.rs"));
}

fn main() {
    println!("=== Full Equilibrium Demo ===");
    println!("Calling C functions from Rust!\n");

    unsafe {
        // Arithmetic operations
        println!("Arithmetic:");
        println!("  10 + 5 = {}", ffi::calc_add(10, 5));
        println!("  10 - 5 = {}", ffi::calc_subtract(10, 5));
        println!("  10 * 5 = {}", ffi::calc_multiply(10, 5));
        println!("  10.0 / 5.0 = {:.2}", ffi::calc_divide(10.0, 5.0));

        // Advanced operations
        println!("\nAdvanced:");
        println!("  2^8 = {}", ffi::calc_power(2, 8));
        println!("  sqrt(144) = {:.2}", ffi::calc_sqrt(144.0));
        println!("  sqrt(2) = {:.10}", ffi::calc_sqrt(2.0));
    }

    println!("\n✓ All C functions called successfully!");
    println!("\nThis demonstrates:");
    println!("  - C code compiled via cc crate");
    println!("  - Rust FFI declarations generated by equilibrium-ffi");
    println!("  - Calling C functions from Rust");
}
